### ISSUE TITLE
Offer helper to download calendar file for his/her shifts

### ISSUE THREAD

**Issue by EllenMaeckelburg** [helfertool/helfertool#1]
After submitting the registration form, the shifts are shown. It would be great, to have a calendar file generated, that includes all those shifts and the necessary details like location and maybe the name of the administratior.

**Comment by svenhertle** [comment]
The export was added in 52e3e0ec622950f5992d3d50860a42f1d95c039b

The location of the event is not known. The names of the coordinators/admins are currently not visible to the helpers and therefore are not included in the ics file.
