### ISSUE TITLE
Make pylint clean

### ISSUE THREAD

**Issue by Tomatower** [helfertool/helfertool#12]
Pylint is reporting a lot of nasty things. 

<details><summary>Pylint log for module registration</summary>
<pre>
(helfertool) ~/code/helfertool [helfertool/remotes/upstream/master]% pylint --disable=C,R registration                                           
************* Module registration.urls
W: 68, 0: Anomalous backslash in string: '\-'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W: 73, 0: Anomalous backslash in string: '\-'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W: 78, 0: Anomalous backslash in string: '\-'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W: 83, 0: Anomalous backslash in string: '\-'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W: 88, 0: Anomalous backslash in string: '\-'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W:168, 0: Anomalous backslash in string: '\-'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W:173, 0: Anomalous backslash in string: '\-'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W:178, 0: Anomalous backslash in string: '\-'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W:183, 0: Anomalous backslash in string: '\-'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W:189, 0: Anomalous backslash in string: '\-'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W:204, 0: Anomalous backslash in string: '\-'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W:209, 0: Anomalous backslash in string: '\-'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W:214, 0: Anomalous backslash in string: '\-'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W:224, 0: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W:224, 0: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W:224, 0: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W:234, 0: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W:234, 0: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W:234, 0: Anomalous backslash in string: '\d'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W:  2, 0: Unused include imported from django.conf.urls (unused-import)
************* Module registration.feeds
W: 14, 4: Arguments number differs from overridden 'get_object' method (arguments-differ)
W: 15,20: Unused variable 'shift' (unused-variable)
W: 15,15: Unused variable 'job' (unused-variable)
W: 33,31: Unused argument 'shift' (unused-argument)
W: 36,24: Unused argument 'shift' (unused-argument)
W: 18, 8: Attribute '_helper' defined outside __init__ (attribute-defined-outside-init)
W: 17, 8: Attribute '_event' defined outside __init__ (attribute-defined-outside-init)
W: 19, 8: Attribute '_registered_link' defined outside __init__ (attribute-defined-outside-init)
W:  6, 0: Unused Event imported from models (unused-import)
W:  6, 0: Unused Helper imported from models (unused-import)
************* Module registration.tests
W:  1, 0: Unused TestCase imported from django.test (unused-import)
************* Module registration.utils
I: 14, 0: Locally disabling undefined-variable (E0602) (locally-disabled)
************* Module registration.views.duplicates
W: 25, 4: Redefining name 'duplicates' from outer scope (line 18) (redefined-outer-name)
************* Module registration.views.event
W: 19, 0: TODO shorten (fixme)
************* Module registration.views.helper
E: 46,11: Class 'Shift' has no 'objects' member (no-member)
W: 58,16: Unused variable 'shift' (unused-variable)
W: 58,11: Unused variable 'job' (unused-variable)
W: 93,16: Unused variable 'shift' (unused-variable)
W: 93,11: Unused variable 'job' (unused-variable)
E:125,17: Class 'Shift' has no 'objects' member (no-member)
W:118,11: Unused variable 'job' (unused-variable)
W:152,16: Unused variable 'shift' (unused-variable)
W:181,16: Unused variable 'shift' (unused-variable)
W:181,11: Unused variable 'job' (unused-variable)
W:205,16: Unused variable 'shift' (unused-variable)
W:205,11: Unused variable 'job' (unused-variable)
W:229,11: Unused variable 'job' (unused-variable)
W:265,16: Unused variable 'shift' (unused-variable)
W:330,16: Unused variable 'shift' (unused-variable)
W:330,11: Unused variable 'job' (unused-variable)
************* Module registration.views.export
W: 19,36: Redefining built-in 'type' (redefined-builtin)
E: 54,15: Class 'Shift' has no 'objects' member (no-member)
E: 59,19: Instance of 'list' has no 'filter' member (no-member)
************* Module registration.views.admin
W:  4, 0: Unused fields imported from django.db.models (unused-import)
W:  4, 0: Unused Sum imported from django.db.models (unused-import)
W:  4, 0: Unused F imported from django.db.models (unused-import)
W:  4, 0: Unused ExpressionWrapper imported from django.db.models (unused-import)
W:  9, 0: Unused OrderedDict imported from collections (unused-import)
W: 17, 0: Unused Shift imported from models (unused-import)
************* Module registration.views.permissions
W: 38,19: Unused variable 'created' (unused-variable)
************* Module registration.views.link
W: 24, 4: Redefining name 'links' from outer scope (line 16) (redefined-outer-name)
************* Module registration.views.utils
E: 16,16: Class 'Event' has no 'objects' member (no-member)
E: 21,11: Class 'Event' has no 'DoesNotExist' member (no-member)
************* Module registration.views.registration
E: 19,13: Class 'Event' has no 'objects' member (no-member)
W: 65, 4: Redefining name 'form' from outer scope (line 34) (redefined-outer-name)
E: 42,19: Class 'Link' has no 'objects' member (no-member)
E: 44,16: Class 'Link' has no 'DoesNotExist' member (no-member)
W: 85,16: Unused variable 'shift' (unused-variable)
W: 85,11: Unused variable 'job' (unused-variable)
W: 96,16: Unused variable 'shift' (unused-variable)
W: 96,11: Unused variable 'job' (unused-variable)
W:124, 4: Redefining name 'form' from outer scope (line 34) (redefined-outer-name)
W:115,11: Unused variable 'job' (unused-variable)
W:158, 4: Redefining name 'form' from outer scope (line 34) (redefined-outer-name)
W:151,16: Unused variable 'shift' (unused-variable)
W:151,11: Unused variable 'job' (unused-variable)
W:  1, 0: Unused settings imported from django.conf (unused-import)
W:  5, 0: Unused redirect imported from django.shortcuts (unused-import)
************* Module registration.views.shift
W: 17,23: Unused variable 'helper' (unused-variable)
W: 42,23: Unused variable 'helper' (unused-variable)
************* Module registration.views.job
W: 47,23: Unused variable 'helper' (unused-variable)
W: 85,16: Unused variable 'shift' (unused-variable)
W: 85,23: Unused variable 'helper' (unused-variable)
************* Module registration.models.event
W: 44,-1: String statement has no effect (pointless-string-statement)
E:221,23: Instance of 'Event' has no 'helper_set' member (no-member)
E:241,36: Instance of 'ManyToManyField' has no 'filter' member (no-member)
E:253,19: Instance of 'Event' has no 'job_set' member (no-member)
E:264,32: Value 'self.shirt_sizes' doesn't support membership test (unsupported-membership-test)
E:271,15: Instance of 'Event' has no 'job_set' member (no-member)
E:289,15: Instance of 'Event' has no 'helper_set' member (no-member)
W:309,12: Redefining name 'settings' from outer scope (line 1) (redefined-outer-name)
E:338,12: Class 'InventorySettings' has no 'objects' member (no-member)
W:298,34: Unused argument 'using' (unused-argument)
W:298, 0: Unused argument 'kwargs' (unused-argument)
W:298,16: Unused argument 'sender' (unused-argument)
************* Module registration.models.helper
E:140,21: Instance of 'ManyToManyField' has no 'all' member (no-member)
E:153,21: Instance of 'ManyToManyField' has no 'all' member (no-member)
E:158,19: Instance of 'Helper' has no 'job_set' member (no-member)
E:169,11: Instance of 'ManyToManyField' has no 'count' member (no-member)
E:174,64: Instance of 'ForeignKey' has no 'url_name' member (no-member)
E:177,58: Instance of 'ForeignKey' has no 'url_name' member (no-member)
E:198,38: Instance of 'ForeignKey' has no 'email' member (no-member)
E:203,11: Instance of 'ManyToManyField' has no 'count' member (no-member)
E:216,15: Instance of 'ForeignKey' has no 'mail_validation' member (no-member)
E:232,17: Instance of 'ManyToManyField' has no 'order_by' member (no-member)
W:239,35: Unused argument 'using' (unused-argument)
W:239,17: Unused argument 'sender' (unused-argument)
W:239, 0: Unused argument 'kwargs' (unused-argument)
W:257,19: Unused argument 'sender' (unused-argument)
W:267, 4: Unused variable 'instance' (unused-variable)
W:265,24: Unused argument 'sender' (unused-argument)
E:278,43: Instance of 'ManyToManyField' has no 'through' member (no-member)
E:279,48: Instance of 'ManyToManyField' has no 'through' member (no-member)
************* Module registration.models.shift
E:107,15: Instance of 'Shift' has no 'helper_set' member (no-member)
E:111,11: Instance of 'ForeignKey' has no 'event' member (no-member)
E:114,19: Instance of 'Shift' has no 'helper_set' member (no-member)
E:135,26: Instance of 'ForeignKey' has no 'event' member (no-member)
E:139,22: Instance of 'Shift' has no 'helper_set' member (no-member)
W:135,12: Unused variable 'size' (unused-variable)
E:153,36: Instance of 'ForeignKey' has no 'event' member (no-member)
E:159,20: Instance of 'ManyToManyField' has no 'all' member (no-member)
W:166,36: Unused argument 'using' (unused-argument)
W:166,18: Unused argument 'sender' (unused-argument)
W:166, 0: Unused argument 'kwargs' (unused-argument)
W: 12, 0: Unused Helper imported from helper (unused-import)
************* Module registration.models.job
E: 79,11: Instance of 'ForeignKey' has no 'archived' member (no-member)
E: 82,19: Instance of 'ManyToManyField' has no 'count' member (no-member)
E: 94,15: Instance of 'ForeignKey' has no 'is_admin' member (no-member)
E: 95,12: Instance of 'ManyToManyField' has no 'filter' member (no-member)
E: 98,18: Class 'Helper' has no 'objects' member (no-member)
E: 99,23: Instance of 'ManyToManyField' has no 'distinct' member (no-member)
E:115,21: Instance of 'Job' has no 'shift_set' member (no-member)
E:148,11: Instance of 'ForeignKey' has no 'badges' member (no-member)
E:149,37: Instance of 'OneToOneField' has no 'duplicate' member (no-member)
E:156,21: Instance of 'Job' has no 'shift_set' member (no-member)
W:163,35: Unused argument 'using' (unused-argument)
W:163,17: Unused argument 'sender' (unused-argument)
W:163, 0: Unused argument 'kwargs' (unused-argument)
************* Module registration.migrations.0004_auto_20160323_1600
W: 19,44: Access to a protected member _default_mail of a client class (protected-access)
************* Module registration.migrations.0015_auto_20161111_1324
W: 19,44: Access to a protected member _default_mail of a client class (protected-access)
************* Module registration.export.excel
W: 34, 0: Anomalous backslash in string: '\ '. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W: 47, 0: Anomalous backslash in string: '\|'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
W:149, 8: Redefining built-in 'format' (redefined-builtin)
************* Module registration.management.commands.closeregistration
E: 15,24: Class 'Event' has no 'objects' member (no-member)
E: 16,19: Class 'Event' has no 'DoesNotExist' member (no-member)
************* Module registration.management.commands.openregistration
E: 15,24: Class 'Event' has no 'objects' member (no-member)
E: 16,19: Class 'Event' has no 'DoesNotExist' member (no-member)
************* Module registration.management.commands.checkdelbug
E:  9,22: Class 'Helper' has no 'objects' member (no-member)
W:  1, 0: Unused CommandError imported from django.core.management.base (unused-import)
************* Module registration.templatetags.duration
W:  7, 4: Unused variable 'total_seconds' (unused-variable)
************* Module registration.forms.helper
W: 46, 4: Arguments number differs from overridden 'save' method (arguments-differ)
E: 88,17: Class 'Shift' has no 'objects' member (no-member)
E:135,15: Class 'Job' has no 'objects' member (no-member)
W:142,19: Unused argument 'commit' (unused-argument)
E:168,45: Class 'Shift' has no 'objects' member (no-member)
************* Module registration.forms.user
E: 24,19: Class 'User' has no 'DoesNotExist' member (no-member)
************* Module registration.forms.link
E: 21,41: Class 'Shift' has no 'objects' member (no-member)
************* Module registration.forms.registration
W: 77,12: Redefining built-in 'id' (redefined-builtin)
E: 73,25: Class 'Shift' has no 'objects' member (no-member)
W:196,12: Redefining built-in 'max' (redefined-builtin)
W:159,38: Lambda may not be necessary (unnecessary-lambda)
E:165,24: Class 'Shift' has no 'objects' member (no-member)
E:198,21: Class 'Shift' has no 'objects' member (no-member)
E:199,21: Class 'Shift' has no 'objects' member (no-member)
E:226,28: Class 'Shift' has no 'objects' member (no-member)
************* Module registration.forms.shift
E: 33,44: Class 'GiftSet' has no 'objects' member (no-member)
************* Module registration.forms.job
W:  7, 0: Unused BadgeRole imported from badges.models (unused-import)
************* Module registration.forms.fields.date
E:  6, 8: Bad first argument 'DateField' given to super() (bad-super-call)
E: 17, 8: Bad first argument 'DateTimeField' given to super() (bad-super-call)

Report
======
2032 statements analysed.

Statistics by type
------------------

+---------+-------+-----------+-----------+------------+---------+
|type     |number |old number |difference |%documented |%badname |
+=========+=======+===========+===========+============+=========+
|module   |75     |78         |-3.00      |NC          |NC       |
+---------+-------+-----------+-----------+------------+---------+
|class    |77     |77         |=          |NC          |NC       |
+---------+-------+-----------+-----------+------------+---------+
|method   |106    |106        |=          |NC          |NC       |
+---------+-------+-----------+-----------+------------+---------+
|function |83     |94         |-11.00     |NC          |NC       |
+---------+-------+-----------+-----------+------------+---------+

External dependencies
---------------------
::

    badges 
      \-models (registration.models.event,registration.models.job,registration.forms.job,registration.models.helper)
    ckeditor 
      \-widgets (registration.forms.event,registration.forms.job)
    django 
      \-conf (registration.views.permissions,registration.templatetags.setting,registration.templatetags.permissions,registration.forms.job,registration.models.event,registration.urls,registration.forms.event,registration.feeds,registration.migrations.0001_initial,registration.models.helper,registration.views.registration)
      | \-urls (registration.urls)
      \-contrib 
      | \-admin (registration.admin)
      | \-auth (registration.views.account)
      | | \-decorators (registration.views.permissions,registration.views.account,registration.views.export,registration.views.job,registration.views.helper,registration.views.shift,registration.decorators.admin,registration.views.event,registration.views.admin,registration.views.link,registration.views.duplicates)
      | | \-forms (registration.views.account,registration.forms.user)
      | | \-models (registration.views.permissions,registration.models.link,registration.models.job,registration.models.event,registration.forms.user)
      | | \-views (registration.urls)
      | \-messages (registration.views.permissions,registration.views.account,registration.views.job,registration.views.helper,registration.views.shift,registration.views.event,registration.views.admin,registration.views.link,registration.views.registration)
      \-core 
      | \-exceptions (registration.models.event,registration.forms.shift,registration.forms.registration,registration.forms.helper)
      | \-files 
      | | \-base (registration.forms.event)
      | \-mail (registration.models.helper)
      | \-management 
      | | \-base (registration.management.commands.closeregistration,registration.management.commands.checkdelbug,registration.management.commands.openregistration)
      | \-urlresolvers (registration.views.permissions,registration.views.job,registration.views.helper,registration.views.shift,registration.views.event,registration.views.admin,registration.feeds,registration.models.helper,registration.views.link,registration.views.registration,registration.views.duplicates)
      | \-validators (registration.models.event,registration.models.shift,registration.migrations.0001_initial)
      \-db 
      | \-migrations (registration.migrations.0014_event_inventory,registration.migrations.0017_auto_20170210_1726,registration.migrations.0012_remove_helper_got_shirt,registration.migrations.0016_auto_20170209_1455,registration.migrations.0002_event_date,registration.migrations.0004_auto_20160323_1600,registration.migrations.0008_auto_20160415_2121,registration.migrations.0006_auto_20160324_0005,registration.migrations.0015_auto_20161111_1324,registration.migrations.0010_shift_gifts,registration.migrations.0009_event_gifts,registration.migrations.0003_auto_20160323_1539,registration.migrations.0018_event_changes_until,registration.migrations.0007_event_ask_news,registration.migrations.0001_initial,registration.migrations.0011_helper_got_shirt,registration.migrations.0005_helper_privacy_statement,registration.migrations.0013_auto_20160704_1214)
      | \-models (registration.migrations.0017_auto_20170210_1726,registration.migrations.0006_auto_20160324_0005,registration.migrations.0010_shift_gifts,registration.migrations.0009_event_gifts,registration.models.link,registration.migrations.0001_initial,registration.migrations.0011_helper_got_shirt,registration.views.duplicates,registration.migrations.0013_auto_20160704_1214,registration.migrations.0014_event_inventory,registration.models.job,registration.models.helper,registration.migrations.0015_auto_20161111_1324,registration.forms.helper,registration.migrations.0016_auto_20170209_1455,registration.migrations.0004_auto_20160323_1600,registration.migrations.0018_event_changes_until,registration.migrations.0007_event_ask_news,registration.models.shift,registration.migrations.0008_auto_20160415_2121,registration.migrations.0002_event_date,registration.migrations.0003_auto_20160323_1539,registration.views.admin,registration.models.event,registration.migrations.0005_helper_privacy_statement)
      |   \-fields (registration.views.admin)
      |   \-functions (registration.views.helper)
      |   \-signals (registration.models.event,registration.models.shift,registration.models.job,registration.models.helper)
      \-dispatch (registration.models.event,registration.models.shift,registration.models.job,registration.models.helper)
      \-forms (registration.forms.duplicates,registration.forms.delete,registration.forms.shift,registration.forms.registration,registration.forms.fields.duallist,registration.forms.job,registration.forms.event,registration.forms.link,registration.forms.fields.date,registration.forms.user,registration.forms.helper)
      \-http (registration.views.permissions,registration.views.export,registration.views.job,registration.views.helper,registration.views.shift,registration.views.utils,registration.views.event,registration.views.admin,registration.views.link,registration.views.registration,registration.views.duplicates)
      \-shortcuts (registration.views.permissions,registration.views.account,registration.views.export,registration.views.job,registration.decorators.archived,registration.views.helper,registration.views.shift,registration.views.utils,registration.views.event,registration.views.admin,registration.views.link,registration.views.registration,registration.views.duplicates)
      \-template (registration.templatetags.registerform_shifts,registration.templatetags.permissions,registration.templatetags.duration,registration.templatetags.setting)
      | \-defaultfilters (registration.models.shift,registration.export.excel)
      | \-loader (registration.models.helper)
      \-test (registration.tests)
      \-utils 
      | \-dateparse (registration.views.export)
      | \-timezone (registration.migrations.0002_event_date,registration.models.shift,registration.models.job)
      | \-translation (registration.export.pdf,registration.views.permissions,registration.views.account,registration.export.excel,registration.forms.user,registration.views.job,registration.forms.registration,registration.forms.shift,registration.views.helper,registration.views.shift,registration.models.job,registration.views.event,registration.views.admin,registration.models.link,registration.models.event,registration.views.link,registration.views.registration,registration.models.shift,registration.forms.helper,registration.models.helper)
      \-views 
        \-generic (registration.urls)
    django_bleach 
      \-models (registration.models.event,registration.models.job,registration.migrations.0001_initial)
    django_ical 
      \-views (registration.feeds)
    gifts 
      \-forms (registration.views.helper)
      \-models (registration.models.event,registration.forms.shift,registration.models.helper)
    inventory 
      \-models (registration.models.event)
      \-utils (registration.views.admin)
    modeltranslation 
      \-translator (registration.translation)
    multiselectfield (registration.models.event)
      \-db 
        \-fields (registration.migrations.0017_auto_20170210_1726)
    news 
      \-helper (registration.views.registration,registration.forms.registration)
    registration (registration.views.permissions,registration.forms.shift,registration.views.export,registration.views.job,registration.forms.registration,registration.views.helper,registration.views.shift,registration.forms.job,registration.views.utils,registration.views.event,registration.views.admin,registration.forms.event,registration.forms.link,registration.views.link,registration.views.registration,registration.views.duplicates,registration.forms.helper)
      \-decorators (registration.views.export,registration.views.job,registration.views.helper,registration.views.shift,registration.views.event,registration.views.admin,registration.views.link,registration.views.duplicates)
      \-export 
      | \-excel 
      | | \-xlsx (registration.views.export)
      | \-pdf 
      |   \-pdf (registration.views.export)
      \-feeds (registration.urls)
      \-forms 
      | \-fields 
      |   \-DatePickerField (registration.forms.event)
      |   \-DateTimePickerField (registration.forms.shift)
      |   \-DualListField (registration.forms.shift)
      |   \-UserSelectField (registration.forms.event,registration.forms.job)
      |   \-duallist (registration.forms.fields.user)
      \-models (registration.admin,registration.decorators.archived,registration.management.commands.closeregistration,registration.management.commands.checkdelbug,registration.feeds,registration.translation,registration.management.commands.openregistration)
      | \-event (registration.models.helper,registration.migrations.0015_auto_20161111_1324,registration.migrations.0004_auto_20160323_1600)
      | \-helper (registration.models.shift,registration.models.job)
      | \-job (registration.models.helper)
      \-templatetags 
      | \-permissions 
      |   \-has_addevent_group (registration.views.event)
      |   \-has_adduser_group (registration.views.admin)
      |   \-has_perm_group (registration.views.admin)
      \-utils (registration.export.excel,registration.views.export,registration.forms.helper)
      \-views (registration.urls)
        \-utils (registration.decorators.admin,registration.feeds)
          \-get_or_404 (registration.views.helper,registration.views.shift,registration.views.registration,registration.views.job)
          \-is_admin (registration.views.event)
          \-is_involved (registration.views.admin)
          \-nopermission (registration.views.permissions,registration.views.export,registration.views.job,registration.views.helper,registration.views.shift,registration.views.event,registration.views.admin,registration.views.link,registration.views.registration,registration.views.duplicates)
    reportlab 
      \-lib 
      | \-colors (registration.export.pdf)
      | \-pagesizes (registration.export.pdf)
      | \-styles (registration.export.pdf)
      | \-units (registration.export.pdf)
      \-platypus (registration.export.pdf)
    xlsxwriter (registration.export.excel)

Raw metrics
-----------

+----------+-------+------+---------+-----------+
|type      |number |%     |previous |difference |
+==========+=======+======+=========+===========+
|code      |3107   |64.35 |3268     |-161.00    |
+----------+-------+------+---------+-----------+
|docstring |315    |6.52  |340      |-25.00     |
+----------+-------+------+---------+-----------+
|comment   |335    |6.94  |353      |-18.00     |
+----------+-------+------+---------+-----------+
|empty     |1071   |22.18 |1124     |-53.00     |
+----------+-------+------+---------+-----------+

Duplication
-----------

+-------------------------+------+---------+-----------+
|                         |now   |previous |difference |
+=========================+======+=========+===========+
|nb duplicated lines      |64    |77       |-13.00     |
+-------------------------+------+---------+-----------+
|percent duplicated lines |1.368 |1.562    |-0.19      |
+-------------------------+------+---------+-----------+

Messages by category
--------------------

+-----------+-------+---------+-----------+
|type       |number |previous |difference |
+===========+=======+=========+===========+
|convention |0      |0        |=          |
+-----------+-------+---------+-----------+
|refactor   |0      |0        |=          |
+-----------+-------+---------+-----------+
|warning    |105    |119      |-14.00     |
+-----------+-------+---------+-----------+
|error      |63     |63       |=          |
+-----------+-------+---------+-----------+

% errors / warnings by module
-----------------------------

+---------------------------------------------------+------+--------+---------+-----------+
|module                                             |error |warning |refactor |convention |
+===================================================+======+========+=========+===========+
|registration.models.helper                         |19.05 |5.71    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.models.job                            |15.87 |2.86    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.models.shift                          |11.11 |4.76    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.models.event                          |11.11 |4.76    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.forms.registration                    |7.94  |2.86    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.views.registration                    |4.76  |11.43   |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.forms.helper                          |4.76  |1.90    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.views.helper                          |3.17  |13.33   |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.views.export                          |3.17  |0.95    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.views.utils                           |3.17  |0.00    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.management.commands.openregistration  |3.17  |0.00    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.management.commands.closeregistration |3.17  |0.00    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.forms.fields.date                     |3.17  |0.00    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.management.commands.checkdelbug       |1.59  |0.95    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.forms.user                            |1.59  |0.00    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.forms.shift                           |1.59  |0.00    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.forms.link                            |1.59  |0.00    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.urls                                  |0.00  |19.05   |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.feeds                                 |0.00  |9.52    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.views.admin                           |0.00  |5.71    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.views.job                             |0.00  |2.86    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.export.excel                          |0.00  |2.86    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.views.shift                           |0.00  |1.90    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.views.permissions                     |0.00  |0.95    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.views.link                            |0.00  |0.95    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.views.event                           |0.00  |0.95    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.views.duplicates                      |0.00  |0.95    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.tests                                 |0.00  |0.95    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.templatetags.duration                 |0.00  |0.95    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.migrations.0015_auto_20161111_1324    |0.00  |0.95    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.migrations.0004_auto_20160323_1600    |0.00  |0.95    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+
|registration.forms.job                             |0.00  |0.95    |0.00     |0.00       |
+---------------------------------------------------+------+--------+---------+-----------+

Messages
--------

+-------------------------------+------------+
|message id                     |occurrences |
+===============================+============+
|no-member                      |60          |
+-------------------------------+------------+
|unused-variable                |32          |
+-------------------------------+------------+
|anomalous-backslash-in-string  |21          |
+-------------------------------+------------+
|unused-argument                |17          |
+-------------------------------+------------+
|unused-import                  |15          |
+-------------------------------+------------+
|redefined-outer-name           |6           |
+-------------------------------+------------+
|redefined-builtin              |4           |
+-------------------------------+------------+
|attribute-defined-outside-init |3           |
+-------------------------------+------------+
|protected-access               |2           |
+-------------------------------+------------+
|bad-super-call                 |2           |
+-------------------------------+------------+
|arguments-differ               |2           |
+-------------------------------+------------+
|unsupported-membership-test    |1           |
+-------------------------------+------------+
|unnecessary-lambda             |1           |
+-------------------------------+------------+
|pointless-string-statement     |1           |
+-------------------------------+------------+
|locally-disabled               |1           |
+-------------------------------+------------+
|fixme                          |1           |
+-------------------------------+------------+

Global evaluation
-----------------
Your code has been rated at 7.93/10 (previous run: 7.99/10, -0.05)

pylint --disable=C,R registration  19.73s user 0.23s system 100% cpu 19.960 total
</pre>
</details>

**Comment by svenhertle** [comment]
884b275 fixes some things.

pylint does not work perfectly with django, pylint-django tries to improve that. The script `./stuff/bin/check-codestyle.sh` runs flake8 and pylint for all modules and shows the results.
