### ISSUE TITLE
`/manage/settings/check/` does not work for invalid mail configurations

### ISSUE THREAD

**Issue by CommanderStorm** [helfertool/helfertool#184]
If the mail configuration does not work, `/manage/settings/check/` does not return a webpage. It just times out.

I had these fields filled with dummy values. This porbably occurs, because you assume that `mail.send.host` and `mail.receive.host` are set corrctly. :)

**Comment by svenhertle** [comment]
Hopefully fixed in c34068a5eba4b14dbddc0d2e9f29c5b8c6b19f36
