### ISSUE TITLE
Send job description in confirmation email

### ISSUE THREAD

**Issue by mhcp6** [helfertool/helfertool#185]
Feature request: Attach the job description to the confirmation email.
Some users don't realize, they have to click on the "i" for this information and will sign on to shifts blindly.

**Comment by CKrebehenne** [comment]
Feature request: Only people that earn an "Essensmarke" should be able to answer/see questions concerning their food preferences.

**Comment by svenhertle** [comment]
I was thinking about introducing another description field for every shift: A short text that is always displayed for important things and the detailed description that we have currently.

**Comment by svenhertle** [comment]
Added field for important notes in 1729fb0720900f7cba9f19e6aebaaafcf2dfea79
