### ISSUE TITLE
AXES Blocking all when running inside a Docker container

### ISSUE THREAD

**Issue by Tomatower** [helfertool/helfertool#2]
All login functionality is blocked, when helfertool/django is running inside of a docker container, because it is blocking the Docker IP: 

```
[05/Apr/2017 14:17:42] "POST /login/ HTTP/1.1" 200 5112
[05/Apr/2017 14:18:29] "POST /login/ HTTP/1.1" 200 5112
[05/Apr/2017 14:19:04] "GET / HTTP/1.1" 200 4051
[05/Apr/2017 14:19:06] "GET /login/ HTTP/1.1" 200 4771
AXES: locked out 172.17.0.1 after repeated login attempts.
[05/Apr/2017 14:19:08] "POST /login/ HTTP/1.1" 403 4071
```

172.17.0.1 is the docker container IP. 

How to configure the Apache-Reverse Proxy that AXES can still work?

**Comment by svenhertle** [comment]
Maybe you have to change the value of `AXES_REVERSE_PROXY_HEADER` in the configuration. The default value according to the [documentation](https://django-axes.readthedocs.io/en/latest/configuration.html) is `HTTP_X_FORWARDED_FOR`, but I changed it to `REMOTE_ADDR` in `settings.py`.

On our server with Apache and uwsgi, `REMOTE_ADDR` ist set, but `X-Forwarded-For` is not set.

**Comment by Tomatower** [comment]
Yay - works, now my public IP is getting blocked :)
