### ISSUE TITLE
OpenID Connect support

### ISSUE THREAD

**Issue by mxmo0rhuhn** [helfertool/helfertool#22]
Thanks for your awesome Tool! We're using it at VSETH (student association of ETH Zurich) for more and more events.

There is just one drawback: With the changing teams the creation of new user accounts and so on very annoying. We would love to link the helfertool to our university log-in via [OpenID Connect](https://openid.net/connect/) and do authentication as well as authorization there. 

This would also enable other people to connect it to own OIDC providers (like a self-hosted Keycloak)  or external providers (like Github, Google and Facebook).

**Comment by svenhertle** [comment]
I like the idea to support OpenID Connect, thanks!

Regarding authorization: Would it be sufficient for you to decide based on claims if a user is allowed to login and if a user is admin? Similar to the LDAP settings where this is decided based on groups: 
https://github.com/helfertool/helfertool/blob/c0fea34843b5f1611d3c5c87aae59cfd70c93329/src/helfertool.yaml#L126-L129

**Comment by mxmo0rhuhn** [comment]
Yes this would be enough for us. Since we control the user management we can define custom claims in a way that it would be useful for the tool.

Sorry for the late response - it's exam time around here.

**Comment by svenhertle** [comment]
I finally managed to finish the OpenID Connect integration :smiley: 

The code is currently on the dev branch and in the dev Docker container. The documentation is here: https://docs.helfertool.org/admin/configuration.html#openid-connect

Please check if it works for you, I tested it with Keycloak.

**Comment by svenhertle** [comment]
OpenID Connect support is now merged to the master branch and part of the `latest` container.
