### ISSUE TITLE
helfertool dev/ops communication platform

### ISSUE THREAD

**Issue by Tomatower** [helfertool/helfertool#46]
Create a discord/slack/mattermost/matrix/newsgroup/forum/undwiesiealleheißen channel for administrators / developers to connect to each other, so we can discuss some of the ideas more efficient than via github issues.

I will do it, what is the preferred protocol?

**Comment by svenhertle** [comment]
Good idea, I created a room on matrix.org: https://matrix.to/#/#helfertool:matrix.org
Will add it to the README
