### ISSUE TITLE
use fuzzy-matching when searching for a helper

### ISSUE THREAD

**Issue by Tomatower** [helfertool/helfertool#48]
proper databases understand fuzzy-matching, so when you search for a helpers name you can do some typos and still find the person (meyer vs maier vs meier vs mayr vs mayer)

References:

**pgsql:** https://www.postgresql.org/docs/current/fuzzystrmatch.html#id-1.11.7.24.6
**mysql:** only the hacky-way: https://lucidar.me/en/web-dev/levenshtein-distance-in-mysql/ and https://stackoverflow.com/questions/13909885/how-to-add-levenshtein-function-in-mysql
**sqlite:** some kind of support: https://www.sqlite.org/spellfix1.html and https://stackoverflow.com/questions/49779281/string-similarity-with-python-sqlite-levenshtein-distance-edit-distance/49815419#49815419
**django:** https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/lookups/#trigram-similarity does not seem to be suited for single-word-searches

but who in their right mind would run it on something else than postgres?
oh wait. stustaculum does.
and development does.

**Comment by svenhertle** [comment]
For PostgreSQL, the TrigramSimilarity seems to the right thing. This documentation contains a bit more details: https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/search/#trigram-similarity
For the other databases, there seems to be no native Django support. For me, it is fine to support this only on PostgreSQL.
