### ISSUE TITLE
[Celery] Badge-Generation failed

### ISSUE THREAD

**Issue by Tomatower** [helfertool/helfertool#5]
Celery failed with the following error, when I try to generate badges (does not matter which):

```
[2017-04-05 17:55:16,751: ERROR/MainProcess] Received unregistered task of type 'badges.tasks.generate_badges'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
'[[1, "1", true], {}, {"callbacks": null, "chain": null, "chord": null, "errbacks": null}]' (89b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/consumer/consumer.py", line 559, in on_task_received
    strategy = strategies[type_]
KeyError: 'badges.tasks.generate_badges'
```

Celery is running as

`su celery -c celery -A helfertool worker -c 2 --loglevel=info`

As backend I have a connected Rabbitmq docker container.

**Comment by svenhertle** [comment]
Did you run celery from the directory that contains `manage.py`? Obviously celery does not find the tasks.

You can get a list of registered tasks with: `celery -A helfertool inspect registered`

It should look like this:
```
->___ celery@freyr: OK
    * badges.tasks.cleanup
    * badges.tasks.cleanup_rm
    * badges.tasks.generate_badges
    * badges.tasks.scale_badge_photo
    * helfertool.celery.debug_task
    * news.tasks.send_news_mails
```

Does the user `celery` have read access to the complete source code?

**Comment by Tomatower** [comment]
I did run celery from the directory with manage.py (`/var/www/helfertool`)

```
root@06fb715250df:/var/www/helfertool# celery -A helfertool inspect registered
-> celery@06fb715250df: OK
    * helfertool.celery.debug_task
```
Does not seem to look right. 


Celery starts with the following output: 

```
root@06fb715250df:/var/www/helfertool# su celery -c "celery -A helfertool worker -c 2 --loglevel=info"
/usr/local/lib/python3.5/dist-packages/celery/backends/amqp.py:68: CPendingDeprecationWarning:
    The AMQP result backend is scheduled for deprecation in     version 4.0 and removal in version v5.0.     Please use RPC backend or a persistent backend.

  alternative='Please use RPC backend or a persistent backend.')

 -------------- celery@06fb715250df v4.0.2 (latentcall)
---- **** -----
--- * ***  * -- Linux-3.16.0-4-amd64-x86_64-with-debian-9.0 2017-04-05 18:19:35
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         helfertool:0x7f6aeadf9080
- ** ---------- .> transport:   amqp://guest:**@rabbitmq:5672//
- ** ---------- .> results:     amqp://
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery


[tasks]
  . helfertool.celery.debug_task

[2017-04-05 18:19:35,486: INFO/MainProcess] Connected to amqp://guest:**@rabbitmq:5672//
[2017-04-05 18:19:35,505: INFO/MainProcess] mingle: searching for neighbors
[2017-04-05 18:19:36,537: INFO/MainProcess] mingle: all alone
[2017-04-05 18:19:36,553: INFO/MainProcess] celery@06fb715250df ready.

```

Where are the celery tasks defined?

**Comment by svenhertle** [comment]
The autodiscovery happens in `helfertool/celery.py` and the tasks are defined in `appname/tasks.py`, so for example `badges/tasks.py`.

The setup was done according to these instructions: http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html

`helfertool/__init__.py` contains the following additional line: `__all__ = ['celery_app']`

The warning about the result backend should not be a problem until now.

Which Python version do you use? (We have Python 3.4.2 and Celery 4.0.2 on our server)

**Comment by Tomatower** [comment]
We have Python 3.5.3 and Celery 4.0.2, so should be compatible. 

It does not seem to find the celery tasks, at which point can I generate a more reasonable error message?

**Comment by svenhertle** [comment]
It also works with Python 3.5.3 on my laptop. `--loglevel=debug` does not seem to add more details about the task discovery.

I updated the code with the changes from the documentation, maybe it fixes the problem for you. (A variable name in settings.py was also changed).

Could you try to run celery with the same user as the Helfertool? Of course they communicate over rabbitmq and celery could also run on another machine, but this would exclude any file permission problem.

**Comment by Tomatower** [comment]
I have pulled the update. 

I have started celery as www-data (the same user as helfertool). All files are owned by www-data. 

And now I get Latex-Errors! This means success!

The solution was that they both have to run as www-data.

**Comment by svenhertle** [comment]
> The solution was that they both have to run as www-data.
Then it is a permission problem, the celery user needs read access to the source code and the settings.py
