### ISSUE TITLE
Enable Helpers to change their shifts themselves until a deadline

### ISSUE THREAD

**Issue by Tomatower** [helfertool/helfertool#7]
a helper has to be able to change his personal data an shifts up to about one week before the event without creating additional workload for us. 

A suggestion is to create the account with email/password at account creation.

**Comment by svenhertle** [comment]
Adding accounts for helpers is some work, especially since we do not want to force the people to create accounts.

Editing the shifts could be done over the link in the email. It contains the UUID, so it is quite hard to guess (`/testevent/registered/853e48fd-e9e9-41c3-8714-a426501d3738/`)

**Comment by Tomatower** [comment]
Is this already implemented, or is this a concept?

**Comment by svenhertle** [comment]
It is not implemented yet.

**Comment by Tomatower** [comment]
Where would you suggest to start implementing it (I am fairly new to Django)?

**Comment by svenhertle** [comment]
Since this is also a very interesting feature for us, I'm working on it right now ;)

**Comment by Tomatower** [comment]
I have seen commit https://github.com/helfertool/helfertool/commit/54d5158dd8eaca676d524c27db0e414966f21976 - it seems to be exactly what we need, I will start testing it soon

How do you plan on recovering lost links, for example when a user has lost the email and asks the team to give him the link?

**Comment by svenhertle** [comment]
I will add a button to resend the confirmation mail (this is on the todo list since a while).

**Comment by Nos-** [comment]
Hi,
this sounds very nice. Is it already implemented now?

**Comment by svenhertle** [comment]
The button to resend the confirmation mail is implemented.

This issue is still open since helpers can edit and delete their registration on their own, but not add further shifts (but they can of course register again)
